name: navigation
version: 0.0.1
publish_to: none
description: Navigation package.

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #main dependencies
  core:
    path: ../core
  domain:
    path: ../domain
  core_ui:
    path: ../core_ui

  #FEATURES

  #common
  settings:
    path: ../features/common/settings
  sign_in_screen:
    path: ../features/common/sign_in_screen
  sign_up_screen:
    path: ../features/common/sign_up_screen
  main_screen:
    path: ../features/common/main_screen

  #user
  user_home:
    path: ../features/user/user_home
  dishes_menu:
    path: ../features/user/dishes_menu
  order_history:
    path: ../features/user/order_history
  shopping_cart:
    path: ../features/user/shopping_cart
  detailed_page:
    path: ../features/user/detailed_page

  #admin
  admin_home:
    path: ../features/admin/admin_home
  admin_menu:
    path: ../features/admin/admin_menu
  users:
    path: ../features/admin/users

  #user manager
  user_manager_home:
    path: ../features/managers/user_manager/user_manager_home

  #order manager
  order_manager_home:
    path: ../features/managers/order_manager/order_manager_home

  #catalogue manager
  catalogue_manager_home:
    path: ../features/managers/catalogue_manager/catalogue_manager_home
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
