name: catalogue_manager_home
version: 0.0.1
publish_to: none
description: Catalogue manager screen library.

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../../../core
  core_ui:
    path: ../../../../core_ui

  settings:
    path: ../../../common/settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
