name: core
version: 0.0.1
publish_to: none
description: Project package that represents dependencies.

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_lints: ^3.0.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  flutter_bloc: ^8.1.5
  cloud_firestore: ^4.17.0
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.2.6
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.2
  auto_route: ^8.0.3
  lottie: ^3.1.0
  animations: ^2.0.11
  uuid: ^4.4.0

  core_ui:
    path: ../core_ui

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
